# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout\mainView.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(776, 591)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.file1_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.file1_lineEdit.setObjectName("file1_lineEdit")
        self.horizontalLayout.addWidget(self.file1_lineEdit)
        self.file1_button = QtWidgets.QPushButton(self.centralwidget)
        self.file1_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.file1_button.setIcon(icon1)
        self.file1_button.setObjectName("file1_button")
        self.horizontalLayout.addWidget(self.file1_button)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.swap_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swap_button.sizePolicy().hasHeightForWidth())
        self.swap_button.setSizePolicy(sizePolicy)
        self.swap_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.swap_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/swap.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.swap_button.setIcon(icon2)
        self.swap_button.setIconSize(QtCore.QSize(32, 32))
        self.swap_button.setObjectName("swap_button")
        self.gridLayout.addWidget(self.swap_button, 0, 0, 2, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.file2_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.file2_lineEdit.setObjectName("file2_lineEdit")
        self.horizontalLayout_2.addWidget(self.file2_lineEdit)
        self.file2_button = QtWidgets.QPushButton(self.centralwidget)
        self.file2_button.setText("")
        self.file2_button.setIcon(icon1)
        self.file2_button.setObjectName("file2_button")
        self.horizontalLayout_2.addWidget(self.file2_button)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.create_button = QtWidgets.QPushButton(self.centralwidget)
        self.create_button.setObjectName("create_button")
        self.gridLayout.addWidget(self.create_button, 2, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 776, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuApp = QtWidgets.QMenu(self.menuBar)
        self.menuApp.setObjectName("menuApp")
        MainWindow.setMenuBar(self.menuBar)
        self.app_update_button = QtWidgets.QAction(MainWindow)
        self.app_update_button.setObjectName("app_update_button")
        self.menuApp.addAction(self.app_update_button)
        self.menuBar.addAction(self.menuApp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gestione Inventario"))
        self.create_button.setText(_translate("MainWindow", "Crea File"))
        self.menuApp.setTitle(_translate("MainWindow", "App"))
        self.app_update_button.setText(_translate("MainWindow", "Update"))
import resources_rc
